// Esquema de la base de datos (PostgreSQL). Cada entrada de MIGRATIONS se aplica una
// sola vez (tabla schema_migrations), así las bases existentes se actualizan solas.

const NOW = `to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')`;
const ID = 'integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';

export const MIGRATIONS: string[] = [
  /* 1: esquema inicial */ `
  -- Búsquedas sin tildes ni mayúsculas, y por teléfono
  CREATE OR REPLACE FUNCTION norm(t text) RETURNS text LANGUAGE sql IMMUTABLE AS $f$
    SELECT lower(translate(t, 'ÁÀÄÂáàäâÉÈËÊéèëêÍÌÏÎíìïîÓÒÖÔóòöôÚÙÜÛúùüûÑñÇç', 'AAAAaaaaEEEEeeeeIIIIiiiiOOOOooooUUUUuuuuNnCc'))
  $f$;
  CREATE OR REPLACE FUNCTION digits(t text) RETURNS text LANGUAGE sql IMMUTABLE AS $f$
    SELECT regexp_replace(t, '\\D', '', 'g')
  $f$;

  CREATE TABLE users (
    id ${ID},
    name text NOT NULL,
    username text NOT NULL,
    password_hash text NOT NULL,
    role text NOT NULL CHECK (role IN ('admin','employee')),
    active integer NOT NULL DEFAULT 1,
    created_at text NOT NULL DEFAULT ${NOW}
  );
  CREATE UNIQUE INDEX idx_users_username ON users (lower(username));

  CREATE TABLE sessions (
    token_hash text PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at text NOT NULL DEFAULT ${NOW},
    expires_at text NOT NULL
  );

  CREATE TABLE settings (
    key text PRIMARY KEY,
    value text NOT NULL
  );

  CREATE TABLE images (
    id ${ID},
    mime text NOT NULL,
    data bytea NOT NULL,
    created_at text NOT NULL DEFAULT ${NOW}
  );

  CREATE TABLE customers (
    id ${ID},
    name text NOT NULL,
    phone text,
    email text,
    address text,
    birthday text,
    allergens text NOT NULL DEFAULT '[]',
    preferences text,
    notes text,
    created_at text NOT NULL DEFAULT ${NOW},
    updated_at text NOT NULL DEFAULT ${NOW}
  );
  CREATE INDEX idx_customers_phone ON customers(phone);
  CREATE INDEX idx_customers_name ON customers(lower(name));

  CREATE TABLE inventory_items (
    id ${ID},
    name text NOT NULL,
    kind text NOT NULL CHECK (kind IN ('ingredient','material')),
    category text,
    unit text NOT NULL CHECK (unit IN ('g','kg','ml','l','ud')),
    quantity double precision NOT NULL DEFAULT 0,
    min_stock double precision NOT NULL DEFAULT 0,
    cost_per_unit double precision NOT NULL DEFAULT 0,
    pack_size double precision,
    supplier text,
    allergens text NOT NULL DEFAULT '[]',
    notes text,
    active integer NOT NULL DEFAULT 1,
    created_at text NOT NULL DEFAULT ${NOW},
    updated_at text NOT NULL DEFAULT ${NOW}
  );

  CREATE TABLE recipes (
    id ${ID},
    name text NOT NULL,
    category text,
    photo_id integer REFERENCES images(id) ON DELETE SET NULL,
    servings double precision NOT NULL DEFAULT 10 CHECK (servings > 0),
    prep_minutes integer,
    bake_minutes integer,
    temperature integer,
    steps text NOT NULL DEFAULT '[]',
    notes text,
    sale_price double precision,
    created_at text NOT NULL DEFAULT ${NOW},
    updated_at text NOT NULL DEFAULT ${NOW}
  );

  CREATE TABLE recipe_ingredients (
    id ${ID},
    recipe_id integer NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
    item_id integer NOT NULL REFERENCES inventory_items(id) ON DELETE RESTRICT,
    quantity double precision NOT NULL,
    unit text NOT NULL CHECK (unit IN ('g','kg','ml','l','ud')),
    sort integer NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_recipe_ingredients_recipe ON recipe_ingredients(recipe_id);

  CREATE TABLE products (
    id ${ID},
    name text NOT NULL,
    category text NOT NULL,
    description text,
    photo_id integer REFERENCES images(id) ON DELETE SET NULL,
    base_price double precision NOT NULL DEFAULT 0,
    pricing text NOT NULL DEFAULT 'unit' CHECK (pricing IN ('unit','serving')),
    unit_label text NOT NULL DEFAULT 'ud',
    servings double precision NOT NULL DEFAULT 1 CHECK (servings > 0),
    flavors text NOT NULL DEFAULT '[]',
    fillings text NOT NULL DEFAULT '[]',
    coverings text NOT NULL DEFAULT '[]',
    extras text NOT NULL DEFAULT '[]',
    labor_minutes double precision NOT NULL DEFAULT 0,
    other_costs double precision NOT NULL DEFAULT 0,
    stages text,
    active integer NOT NULL DEFAULT 1,
    sort integer NOT NULL DEFAULT 0,
    created_at text NOT NULL DEFAULT ${NOW},
    updated_at text NOT NULL DEFAULT ${NOW}
  );

  CREATE TABLE product_sizes (
    id ${ID},
    product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    name text NOT NULL,
    servings double precision NOT NULL CHECK (servings > 0),
    price double precision NOT NULL DEFAULT 0,
    sort integer NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_product_sizes_product ON product_sizes(product_id);

  CREATE TABLE product_components (
    id ${ID},
    product_id integer NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    recipe_id integer REFERENCES recipes(id) ON DELETE CASCADE,
    item_id integer REFERENCES inventory_items(id) ON DELETE CASCADE,
    quantity double precision NOT NULL DEFAULT 1,
    unit text CHECK (unit IS NULL OR unit IN ('g','kg','ml','l','ud')),
    per_serving integer NOT NULL DEFAULT 0,
    size_id integer REFERENCES product_sizes(id) ON DELETE CASCADE,
    sort integer NOT NULL DEFAULT 0,
    CHECK ((recipe_id IS NULL) <> (item_id IS NULL))
  );
  CREATE INDEX idx_product_components_product ON product_components(product_id);

  CREATE TABLE quotes (
    id ${ID},
    number integer NOT NULL UNIQUE,
    customer_id integer REFERENCES customers(id) ON DELETE SET NULL,
    customer_name text NOT NULL,
    customer_phone text,
    date text NOT NULL,
    valid_until text NOT NULL,
    delivery_date text,
    delivery_time text,
    delivery_type text NOT NULL DEFAULT 'pickup' CHECK (delivery_type IN ('pickup','delivery')),
    delivery_address text,
    delivery_fee double precision NOT NULL DEFAULT 0,
    discount double precision NOT NULL DEFAULT 0,
    total double precision NOT NULL DEFAULT 0,
    allergens text NOT NULL DEFAULT '[]',
    notes text,
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected')),
    order_id integer,
    created_by integer REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT ${NOW},
    updated_at text NOT NULL DEFAULT ${NOW}
  );

  CREATE TABLE orders (
    id ${ID},
    number integer NOT NULL UNIQUE,
    customer_id integer REFERENCES customers(id) ON DELETE SET NULL,
    customer_name text NOT NULL,
    customer_phone text,
    order_date text NOT NULL,
    delivery_date text NOT NULL,
    delivery_time text,
    production_date text,
    delivery_type text NOT NULL DEFAULT 'pickup' CHECK (delivery_type IN ('pickup','delivery')),
    delivery_address text,
    delivery_fee double precision NOT NULL DEFAULT 0,
    discount double precision NOT NULL DEFAULT 0,
    total double precision NOT NULL DEFAULT 0,
    payment_method text,
    status text NOT NULL DEFAULT 'nuevo' CHECK (status IN ('nuevo','confirmado','pendiente','en_preparacion','terminado','entregado','cancelado')),
    allergens text NOT NULL DEFAULT '[]',
    notes text,
    quote_id integer REFERENCES quotes(id) ON DELETE SET NULL,
    stock_consumed_at text,
    confirmed_at text,
    delivered_at text,
    cancelled_at text,
    created_by integer REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT ${NOW},
    updated_at text NOT NULL DEFAULT ${NOW}
  );
  CREATE INDEX idx_orders_delivery ON orders(delivery_date, delivery_time);
  CREATE INDEX idx_orders_status ON orders(status);
  CREATE INDEX idx_orders_customer ON orders(customer_id);
  ALTER TABLE quotes ADD CONSTRAINT quotes_order_fk FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;

  CREATE TABLE order_items (
    id ${ID},
    order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id integer REFERENCES products(id) ON DELETE SET NULL,
    product_name text NOT NULL,
    size_id integer REFERENCES product_sizes(id) ON DELETE SET NULL,
    size_name text,
    quantity double precision NOT NULL DEFAULT 1,
    servings double precision,
    flavor text,
    filling text,
    coverage text,
    decoration text,
    custom_text text,
    extras text NOT NULL DEFAULT '[]',
    unit_price double precision NOT NULL DEFAULT 0,
    line_total double precision NOT NULL DEFAULT 0,
    notes text,
    sort integer NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_order_items_order ON order_items(order_id);

  CREATE TABLE quote_items (
    id ${ID},
    quote_id integer NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
    product_id integer REFERENCES products(id) ON DELETE SET NULL,
    product_name text NOT NULL,
    size_id integer REFERENCES product_sizes(id) ON DELETE SET NULL,
    size_name text,
    quantity double precision NOT NULL DEFAULT 1,
    servings double precision,
    flavor text,
    filling text,
    coverage text,
    decoration text,
    custom_text text,
    extras text NOT NULL DEFAULT '[]',
    unit_price double precision NOT NULL DEFAULT 0,
    line_total double precision NOT NULL DEFAULT 0,
    notes text,
    sort integer NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_quote_items_quote ON quote_items(quote_id);

  CREATE TABLE order_images (
    id ${ID},
    order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    image_id integer NOT NULL REFERENCES images(id) ON DELETE CASCADE,
    sort integer NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_order_images_order ON order_images(order_id);

  CREATE TABLE payments (
    id ${ID},
    order_id integer REFERENCES orders(id) ON DELETE CASCADE,
    kind text NOT NULL CHECK (kind IN ('deposit','payment','refund','direct_sale')),
    amount double precision NOT NULL CHECK (amount >= 0),
    method text NOT NULL,
    description text,
    paid_at text NOT NULL,
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT ${NOW}
  );
  CREATE INDEX idx_payments_order ON payments(order_id);
  CREATE INDEX idx_payments_paid ON payments(paid_at);

  CREATE TABLE expenses (
    id ${ID},
    date text NOT NULL,
    category text NOT NULL,
    description text NOT NULL,
    amount double precision NOT NULL CHECK (amount >= 0),
    supplier text,
    payment_method text,
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT ${NOW}
  );
  CREATE INDEX idx_expenses_date ON expenses(date);

  CREATE TABLE inventory_movements (
    id ${ID},
    item_id integer NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
    type text NOT NULL CHECK (type IN ('purchase','consumption','adjustment','waste')),
    quantity double precision NOT NULL,
    unit_cost double precision,
    order_id integer REFERENCES orders(id) ON DELETE SET NULL,
    expense_id integer REFERENCES expenses(id) ON DELETE SET NULL,
    note text,
    user_id integer REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT ${NOW}
  );
  CREATE INDEX idx_movements_item ON inventory_movements(item_id, created_at);
  CREATE INDEX idx_movements_order ON inventory_movements(order_id);
  CREATE INDEX idx_movements_expense ON inventory_movements(expense_id);

  CREATE TABLE production_tasks (
    id ${ID},
    order_id integer NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    order_item_id integer REFERENCES order_items(id) ON DELETE CASCADE,
    stage text NOT NULL CHECK (stage IN ('preparar','hornear','rellenar','decorar','empaquetar','entregar')),
    title text NOT NULL,
    done integer NOT NULL DEFAULT 0,
    done_at text,
    done_by integer REFERENCES users(id) ON DELETE SET NULL,
    sort integer NOT NULL DEFAULT 0
  );
  CREATE INDEX idx_tasks_order ON production_tasks(order_id);

  CREATE TABLE shopping_extras (
    id ${ID},
    name text NOT NULL,
    quantity text,
    item_id integer REFERENCES inventory_items(id) ON DELETE SET NULL,
    done integer NOT NULL DEFAULT 0,
    done_at text,
    created_at text NOT NULL DEFAULT ${NOW}
  );

  CREATE TABLE shopping_checks (
    item_id integer PRIMARY KEY REFERENCES inventory_items(id) ON DELETE CASCADE,
    checked_at text NOT NULL DEFAULT ${NOW}
  );

  CREATE TABLE reminders (
    id ${ID},
    text text NOT NULL,
    due_date text,
    order_id integer REFERENCES orders(id) ON DELETE CASCADE,
    done integer NOT NULL DEFAULT 0,
    created_by integer REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT ${NOW}
  );

  -- Copias de seguridad (datos comprimidos en JSON)
  CREATE TABLE backups (
    id ${ID},
    name text NOT NULL,
    kind text NOT NULL,
    size integer NOT NULL,
    data bytea NOT NULL,
    created_at text NOT NULL DEFAULT ${NOW}
  );
  `,
  /* 2: funciones de búsqueda con search_path fijo (recomendación de seguridad de Supabase) */ `
  ALTER FUNCTION norm(text) SET search_path = pg_catalog;
  ALTER FUNCTION digits(text) SET search_path = pg_catalog;
  `,
];

/** Tablas con datos del negocio, en orden de dependencias (para copias y restauración). */
export const DATA_TABLES = [
  'users',
  'settings',
  'customers',
  'inventory_items',
  'recipes',
  'recipe_ingredients',
  'products',
  'product_sizes',
  'product_components',
  'quotes',
  'orders',
  'order_items',
  'quote_items',
  'order_images',
  'payments',
  'expenses',
  'inventory_movements',
  'production_tasks',
  'shopping_extras',
  'shopping_checks',
  'reminders',
] as const;
